version: '3.0'

services:
  youtuberino:
    build: 
      context: .
      dockerfile: bot/Dockerfile
    container_name: youtube-telegram-bot
    environment:
      TELEGRAM_BOT_TOKEN: 5449367848:AAH3fCtqxv1Ryhp1zXI8C1jJEbMyvpff0rw
      ALLOWED_CHAT_ID: 958468633
    restart: always