version: '3.0'

services:
  youtuberino:
    build: 
      context: .
      dockerfile: bot/Dockerfile
    container_name: youtube-telegram-bot
    environment:
      - TELEGRAM_BOT_TOKEN=5449367848:AAGy8eU4JzkiWQiUX9-p5hHiBUWRBJ2brAM
      - ALLOWED_CHAT_ID=958468633
      - DEBUG="1"
    restart: always