FROM python:3.8-alpine
LABEL it.420blazeit.youtube-dl.spolli="kebabnopiccante@gmail.com"

COPY requirements.txt /app/requirements.txt
COPY main.py /app/main.py

WORKDIR /app

RUN apk update && apk add ffmpeg --no-cache \
    && rm -rf /var/cache/apk/* \
	&& pip install -r /app/requirements.txt \
	&& chmod +x /app/main.py \
	&& mkdir /app/download

ENTRYPOINT ["/app/main.py"]
